In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('bosh_2024-07-24-20-06-10.csv')

In [28]:
data.head()

,exp_no,n_users,code_length,collusion_size,confidence,detected_tot,detected_correct,detected_incorrect,undetected
0,0,10,64,2,0.3,2,2,0,0
1,0,10,64,2,0.5,2,2,0,0
2,0,10,64,2,1.0,2,2,0,0
3,0,10,64,2,1.5,1,1,0,1
4,0,10,64,3,0.3,3,3,0,0

In [3]:
# Calculate the ratios
data['ratio_incorrect_tot'] = data['detected_incorrect'] / data['detected_tot']
data['ratio_correct_collusion'] = data['detected_correct'] / data['collusion_size']

# Group by the required combinations
grouped_data = data.groupby(['collusion_size', 'confidence', 'n_users', 'code_length']).agg(
    mean_ratio_incorrect_tot=('ratio_incorrect_tot', 'mean'),
    std_ratio_incorrect_tot=('ratio_incorrect_tot', 'std'),
    mean_ratio_correct_collusion=('ratio_correct_collusion', 'mean'),
    std_ratio_correct_collusion=('ratio_correct_collusion', 'std'),
    count_detected_correct_gt_0=('detected_correct', lambda x: (x > 0).sum())
).reset_index()

In [30]:
grouped_data

,collusion_size,confidence,n_users,code_length,mean_ratio_incorrect_tot,std_ratio_incorrect_tot,mean_ratio_correct_collusion,std_ratio_correct_collusion,count_detected_correct_gt_0
0,2,0.3,10,16,0.486667,0.212684,0.900,0.210819,10
1,2,0.3,10,32,0.441667,0.136366,0.950,0.158114,10
2,2,0.3,10,64,0.158333,0.183174,1.000,0.000000,20
3,2,0.3,10,128,0.033333,0.105409,1.000,0.000000,10
4,2,0.3,10,256,0.000000,0.000000,1.000,0.000000,10
...,...,...,...,...,...,...,...,...,...
731,100,1.5,1000,128,0.680696,0.048595,0.199,0.037845,10
732,100,1.5,1000,256,0.518929,0.040438,0.328,0.047093,10
733,100,1.5,1000,512,0.378209,0.048143,0.459,0.040675,10
734,100,1.5,1000,1024,0.169902,0.036149,0.664,0.044771,10
735,100,1.5,1000,2048,0.048993,0.021657,0.859,0.032472,10

In [9]:
filtered_data = grouped_data[(grouped_data['code_length'] == 512) &
                             (grouped_data['n_users'] == 10)]
filtered_data[['count_detected_correct_gt_0', 'mean_ratio_incorrect_tot', 'std_ratio_incorrect_tot',
               'mean_ratio_correct_collusion', 'std_ratio_correct_collusion']].round(2).to_csv('filtered_1.csv', index=False)

In [10]:
filtered_data

,collusion_size,confidence,n_users,code_length,mean_ratio_incorrect_tot,std_ratio_incorrect_tot,mean_ratio_correct_collusion,std_ratio_correct_collusion,count_detected_correct_gt_0
5,2,0.3,10,512,0.0,0.0,1.000000,0.000000,10
29,2,0.5,10,512,0.0,0.0,1.000000,0.000000,10
53,2,1.0,10,512,0.0,0.0,1.000000,0.000000,10
77,2,1.5,10,512,0.0,0.0,1.000000,0.000000,10
101,3,0.3,10,512,0.0,0.0,1.000000,0.000000,10
125,3,0.5,10,512,0.0,0.0,1.000000,0.000000,10
149,3,1.0,10,512,0.0,0.0,1.000000,0.000000,10
173,3,1.5,10,512,0.0,0.0,0.533333,0.172133,10
197,4,0.3,10,512,0.0,0.0,1.000000,0.000000,10
221,4,0.5,10,512,0.0,0.0,1.000000,0.000000,10
245,4,1.0,10,512,0.0,0.0,0.925000,0.120761,10
269,4,1.5,10,512,0.0,0.0,0.050000,0.105409,2
293,5,0.3,10,512,0.0,0.0,1.000000,0.000000,10
317,5,0.5,10,512,0.0,0.0,1.000000,0.000000,10
341,5,1.0,10,512,0.0,0.0,0.500000,0.105409,10
365,5,1.5,10,512,NaN,NaN,0.000000,0.000000,0
389,10,0.3,10,512,0.0,0.0,0.420000,0.078881,10
413,10,0.5,10,512,0.0,0.0,0.310000,0.073786,10
437,10,1.0,10,512,0.0,0.0,0.190000,0.056765,10
461,10,1.5,10,512,0.0,0.0,0.060000,0.051640,6

In [ ]:
# hit = count(detected_correct>0)
# FPR = detected_incorrect/detected_tot
# recall = detected_correct/collusion_size

In [37]:
# result = p.groupby(['collusion_size', 'confidence']).agg(
#     mean_ratio=('ratio', 'mean'),
#     std_ratio=('ratio', 'std')
# ).reset_index()